### ISSUE TITLE
Manual changing of the charge balance

### ISSUE THREAD

**Issue by NewAdventure00777** [opensource-socialnetwork/Wallet#2]
I did a manual change of the member's balance and it changed this member's wallet page. The system gave the member a message earlier that to wait as the system is doing repair or to contact the admin.  But I waited for over 8 hours and nothing happened.  However, today it showed this image.  The wallet overview of this specific member is still messed up.  
![member-area-wallet-issue-2](https://github.com/user-attachments/assets/b5cf3eed-1b58-4526-b77b-7ce68633152b)

**Comment by marks909** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by lianglee** [comment]
This doesn't relates here,  did you actually disabled cache when doing changes to your site?

**Comment by NewAdventure00777** [comment]
No.  The admin and other members' wallet page looked fine.  but only this specific member after I did some manual charging.

**Comment by NewAdventure00777** [comment]
Hi,
I did submit this issue to Github for suggestions.

________________________________

**Comment by lianglee** [comment]
Please use community for discussion the bug is in your code not in wallet
sir.

**Comment by NewAdventure00777** [comment]
Okay.  This is the admin page looks right now.



________________________________
